#!/bin/bash

# Format: "<formula|cask>:<name>[:<tap>]"
# Examples:
# "formula:mycli"
# "formula:im-select:daipeihust/tap"
# "cask:foo-bar:some/tap"
BREW_ITEMS=(
	"formula:mycli"
	"formula:wget"
	"formula:git"
	"formula:tig"
	"formula:cloc"
	"formula:ctop"
	"formula:gibo"
	"formula:bat"
	"formula:lazygit"
	"formula:zoxide"
	"formula:trash"
	"formula:htop"
	"formula:bottom"
	"formula:nmap"
	"formula:uv"
	"cask:google-chrome"
	"cask:cheatsheet"
	"cask:itsycal"
	"cask:browserosaurus"
	"cask:thor"
	"cask:iterm2"
	"cask:spotify"
	"cask:devtoys"
	"cask:ghostty"
	"cask:obsidian"
	"cask:claude-code"
	"cask:geph"
	"cask:visual-studio-code"
	"cask:codex"
	"cask:codex-app"
	"cask:codeisland"
	"cask:masscode"
)
